IPM-49 Реализовать сервис получения списка бумаг
IPLATFORM-DS/iplatform-moex-2 pull request #56
Opened 2022-08-18 11:35 UTC by QayTem

2022-08-19 06:16 UTC, a-s-eliseev requested changes

2022-08-19 06:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/iplatformmoex/client/SecuritiesClient.java
> +public interface SecuritiesClient {
название классов и интерфейсов в единственном числе

2022-08-19 06:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/iplatformmoex/controller/SecuritiesController.java
> +public class SecuritiesController {
название классов и интерфейсов в единственном числе

2022-08-19 06:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/iplatformmoex/services/SecuritiesService.java
> +public class SecuritiesService {
название классов и интерфейсов в единственном числе

2022-08-19 06:16 UTC, a-s-eliseev commented on pom.xml
> +    <dependencyManagement>
а нужна ли эта зависимость?

2022-08-19 06:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/iplatformmoex/client/SecuritiesClient.java
> +@FeignClient(value = "moex-iss", url = "https://iss.moex.com/iss")
все адреса должны храниться в отдельном файле, на это есть отдельная задача

2022-08-19 06:16 UTC, a-s-eliseev commented on src/main/java/space/eliseev/iplatformmoex/controller/SecuritiesController.java
> +                                @RequestParam(required = false) String engine,
некоторые параметры (engine, market) - это enum

2022-08-19 11:00 UTC, QayTem commented on src/main/java/space/eliseev/iplatformmoex/client/SecuritiesClient.java
> +@FeignClient(value = "moex-iss", url = "https://iss.moex.com/iss")
я просто делаю их в разных ветках как вы говорили каждую задачу в новой ветке, надо делать эти задачи в одной ветке?

2022-08-26 15:37 UTC, a-s-eliseev approved these changes

2022-08-26 15:52 UTC, a-s-eliseev approved these changes

2022-08-26 15:52 UTC, merged